# Generated by Django 3.2.8 on 2021-12-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='logo.jpg', upload_to='Blog'),
        ),
    ]
